version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
      - image: circleci/python:3.7.0
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

#      - restore_cache:
#          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: 
          name: mvn-clean
          command: mvn clean
      
      - run: 
          name: mvn-install
          command: mvn install
      
      - run: 
          name: mvn-test
          command: mvn test

      - run: 
          name: Install Command Line
          command: echo "sudo apt-get -y -qq install awscli; "

#      - run: 
#          name: echo 
#          command: find . -name "*.*";pwd;mkdir target/sam;cp target/demo-0.0.1-SNAPSHOT.jar target/sam/.;cd target;pwd;aws --version;

      - run: 
          name: Deploy to Prod
          command: echo "chmod 755 ./deploy.sh; ./deploy.sh"
#          command: aws s3 sync target s3://s3circleci/ --delete

#  build:
#    docker:
#       - image: account-id.dkr.ecr.us-east-1.amazonaws.com/org/repo:0.1
#          aws_auth:
#	    aws_access_key_id: $AWS_ACCESS_KEY_ID_STAGING
#	    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_STAGING
#    steps:
#      - run:
#         name: "Full Test Suite"
#	 command: "testing...."
       
###
#      - run: mvn dependency:go-offline
#      
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
#      
#      - run: mvn package
#      
#      - store_test_results:
#          path: target/surefire-reports
#      
#      - store_artifacts:
#          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
#
############
